services:

  postgres_container:
    image: postgres:15-alpine
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_DB=socialized
        - POSTGRES_USER=mykyta
        - POSTGRES_PASSWORD=Pass1234!
    restart: always
    volumes:
      - socialized_db_data:/var/lib/postgresql/data
    
  backend_socialized:
    container_name: backend_socialized
    build:
      context: ./src/Socialized.Backend/
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY-}socalized-api
    ports:
        - "8080:8080"
    restart: on-failure
    environment:
      - ConnectionStrings__DefaultConnection=host=socialized-db-server.postgres.database.azure.com;Port=5432;Database=socialized;Username=mykyta;Password=Pass1234!;Pooling=true;

  frontend_socialized:
    container_name: frontend_socialized
    build:
      context: ./src/Socialized.Frontend/
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY-}socalized-frontend
    ports:
      - "5173:5173"
    restart: on-failure
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend_socialized
  
volumes:
  socialized_db_data: